// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = chai.assert;

  describe('deck', function() {
    var deck, hand;
    deck = null;
    hand = null;
    beforeEach(function() {
      var dealerHand, playerHand;
      deck = new Deck();
      dealerHand = deck.dealPlayer();
      return playerHand = deck.dealPlayer();
    });
    return it('should give a max score', function() {
      var scores;
      console.log(dealerHand);
      scores = deck.get('dealerHand').maxScore();
      return assert.strictEqual(scores.length, 1);
    });
  });

}).call(this);

//# sourceMappingURL=BlackjackViewSpec.map
