// Generated by CoffeeScript 1.7.1
(function() {
  var assert;

  assert = chai.assert;

  describe("hand collection", function() {
    it("should remove cards from deck on a hit", function() {
      var collection, playerHand;
      collection = new Deck();
      playerHand = collection.dealPlayer();
      playerHand.hit();
      return assert.strictEqual(collection.length, 49);
    });
    it("should remove the last card of the deck on a hit", function() {
      var collection, lastCard, playerHand;
      collection = new Deck();
      playerHand = collection.dealPlayer();
      lastCard = collection.models[49];
      playerHand.hit();
      return assert.strictEqual(lastCard, playerHand.models[2]);
    });
    it("should return 1 score", function() {
      var collection, playerHand, score;
      collection = new Deck();
      playerHand = collection.dealPlayer();
      score = [];
      score.push(playerHand.maxScores());
      return assert.strictEqual(score.length, 1);
    });
    return it("should bust if player goes over 21", function() {
      var collection, playerHand;
      collection = new Deck();
      playerHand = collection.dealPlayer();
      playerHand.hit();
      playerHand.hit();
      playerHand.hit();
      playerHand.hit();
      return assert.strictEqual(playerHand.busted(), true);
    });
  });

}).call(this);

//# sourceMappingURL=CardSpec.map
