// Generated by CoffeeScript 1.7.1
(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Hand = (function(_super) {
    __extends(Hand, _super);

    function Hand() {
      return Hand.__super__.constructor.apply(this, arguments);
    }

    Hand.prototype.model = Card;

    Hand.prototype.initialize = function(array, deck, isDealer) {
      this.deck = deck;
      this.isDealer = isDealer;
    };

    Hand.prototype.hit = function() {
      this.add(this.deck.pop()).last();
      if (this.busted()) {
        return this.trigger('bust', this);
      }
    };

    Hand.prototype.scores = function() {
      var hasAce, score;
      hasAce = this.reduce(function(memo, card) {
        return memo || card.get('value') === 1;
      }, false);
      score = this.reduce(function(score, card) {
        return score + (card.get('revealed') ? card.get('value') : 0);
      }, 0);
      if (hasAce) {
        return [score, score + 10];
      } else {
        return [score];
      }
    };

    Hand.prototype.busted = function() {
      return this.maxScores() > 21;
    };

    Hand.prototype.maxScores = function() {
      var scores;
      scores = this.scores();
      if (scores.length > 1) {
        if (scores[1] < 22) {
          return scores[1];
        } else {
          return scores[0];
        }
      } else {
        return scores[0];
      }
    };

    Hand.prototype.playTo17 = function() {
      this.models[0].flip();
      while (this.maxScores() < 17) {
        this.hit();
      }
      if (!this.busted()) {
        return this.stand();
      }
    };

    Hand.prototype.stand = function() {
      return this.trigger('stand', this);
    };

    return Hand;

  })(Backbone.Collection);

}).call(this);

//# sourceMappingURL=Hand.map
