// Generated by CoffeeScript 1.7.1
var assert;

assert = chai.assert;

describe('app', function() {
  var dealerHand, deck, hand, playerHand;
  deck = null;
  hand = null;
  dealerHand = null;
  playerHand = null;
  beforeEach(function() {
    deck = new Deck();
    dealerHand = deck.dealDealer();
    return playerHand = deck.dealPlayer();
  });
  return it("should play dealer\'s hand on a player stand event", function() {
    var afterScore, beforeScore;
    beforeScore = dealerHand.maxScores();
    playerHand.trigger('stand');
    afterScore = dealerHand.maxScores();
    return assert.notEqual(beforeScore, afterScore);
  });
});
