// Generated by CoffeeScript 1.7.1
var assert;

assert = chai.assert;

describe('deck constructor', function() {
  var deck, hand;
  deck = null;
  hand = null;
  beforeEach(function() {
    deck = new Deck();
    return hand = deck.dealPlayer();
  });
  return describe('deck', function() {
    it("should create a card collection", function() {
      var collection;
      collection = new Deck();
      return assert.strictEqual(collection.length, 52);
    });
    it("should deal from the deck", function() {
      var collection, playerHand;
      collection = new Deck();
      playerHand = collection.dealPlayer();
      return assert.strictEqual(collection.length, 50);
    });
    return it("should hide the first card after dealing the dealer's hand", function() {
      var collection, dealerHand;
      collection = new Deck();
      dealerHand = collection.dealDealer();
      return assert.strictEqual(dealerHand.models[0].get('revealed'), false);
    });
  });
});
